# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: Default

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '.'  # Archive everything in the repo
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/app.zip'
    displayName: 'Archive files'

  # Step 5: Publish the archive as an artifact
- publish: $(Build.ArtifactStagingDirectory)/app.zip
  artifact: drop
  displayName: 'Publish artifact'

  # Step 6: Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'maaz_service'  # Name of your service connection
    appType: 'webAppLinux'  # Use 'webApp' if it's a Windows app
    appName: 'NodejsApp'  # Name of your Azure Web App
    package: '$(Build.ArtifactStagingDirectory)/app.zip'
    runtimeStack: 'NODE|16-lts'  # Adjust to match your Node.js version on Azure
    displayName: 'Deploy to Azure Web App'
